// Generated by KLSL compiler v0.1
// Shader: fold_adam

StructuredBuffer<float> grad_w : register(t0);
StructuredBuffer<float> m_in : register(t1);
StructuredBuffer<float> v_in : register(t2);
RWStructuredBuffer<float> weights : register(u0);
RWStructuredBuffer<float> m_out : register(u1);
RWStructuredBuffer<float> v_out : register(u2);
ConstantBuffer<AdamConst> cb : register(b0);

// adam.klsl — Adam optimizer weight update
// Reads m/v/step state from previous buffers, applies Adam update, writes new weights
// Compile: klslc adam.klsl




// AdamConst: uint n_shard, step; float lr, beta1, beta2, eps

[numthreads(32, 1, 1)]
void fold_adam(uint3 SV_DispatchThreadID : SV_DispatchThreadID)
{
    uint tid = SV_DispatchThreadID.x;
    if (tid >= cb.n_shard) return;

    float g = grad_w[tid];

    // First moment: m = beta1*m + (1-beta1)*g
    float m = cb.beta1 * m_in[tid] + (1.0f - cb.beta1) * g;
    // Second moment: v = beta2*v + (1-beta2)*g^2
    float v = cb.beta2 * v_in[tid] + (1.0f - cb.beta2) * g * g;

    // Bias correction
    float bc1  = 1.0f - pow(cb.beta1, (float)cb.step);
    float bc2  = 1.0f - pow(cb.beta2, (float)cb.step);
    float m_hat = m / bc1;
    float v_hat = v / bc2;

    // Weight update: w -= lr * m_hat / (sqrt(v_hat) + eps)
    float delta = cb.lr * m_hat / (sqrt(v_hat) + cb.eps);
    weights[tid] -= delta;
    m_out[tid] = m;
    v_out[tid] = v;
}


