// Generated by KLSL compiler v0.1
// Shader: fold_backward

StructuredBuffer<float> grad_out : register(t0);
StructuredBuffer<float> fwd_hidden : register(t1);
StructuredBuffer<float> weights : register(t2);
RWStructuredBuffer<float> grad_w : register(u0);
ConstantBuffer<BwdConst> cb : register(b0);

// backward.klsl — xshard fold backward pass (xshard-backward grad format)
// Reads fwd_hidden from SHM binding, computes weight gradients, clips by L2 norm
// Compile: klslc backward.klsl




// BwdConst: uint seq_len, n_embd, n_shard; float grad_clip, grad_scale

[numthreads(32, 1, 1)]
void fold_backward(uint3 SV_DispatchThreadID : SV_DispatchThreadID)
{
    uint tid = SV_DispatchThreadID.x;
    if (tid >= cb.n_shard) return;

    // d_hidden = grad_out @ weights[tid] (reverse lm_head)
    float d_h = 0.0f;
    for (uint s = 0; s < cb.seq_len; ++s) {
        d_h += grad_out[s] * weights[s * cb.n_shard + tid];
    }

    // SwiGLU gradient: silu_grad * gate_grad
    float h   = fwd_hidden[tid];
    float sig = 1.0f / (1.0f + exp(-h));
    float silu_grad = sig * (1.0f + h * (1.0f - sig));
    float d_w = d_h * silu_grad * cb.grad_scale;

    // L2-norm gradient clip (applied per-shard element; full norm needs reduction)
    float g_norm = abs(d_w);
    float clip   = (g_norm > cb.grad_clip) ? (cb.grad_clip / g_norm) : 1.0f;
    grad_w[tid] = d_w * clip;
}


