// Generated by KLSL compiler v0.1
// Shader: fold_clamp

StructuredBuffer<float> tensor_in : register(t0);
RWStructuredBuffer<float> tensor_out : register(u0);
ConstantBuffer<ClampConst> cb : register(b0);

// fold_clamp.klsl — gradient / activation clamping
// mode 0: L2-norm grad clip (--grad-clip 1.0)
// mode 1: element-wise hard clamp (for logits / activations)
// Compile: klslc fold_clamp.klsl




// ClampConst: uint n, mode; float clip_norm, clip_lo, clip_hi

[numthreads(64, 1, 1)]
void fold_clamp(uint3 SV_DispatchThreadID : SV_DispatchThreadID)
{
    uint tid = SV_DispatchThreadID.x;
    if (tid >= cb.n) return;

    float x = tensor_in[tid];

    // mode 0: grad-norm clip
    if (cb.mode == 0u) {
        float g_norm = abs(x);
        float ratio  = (g_norm > cb.clip_norm) ? (cb.clip_norm / g_norm) : 1.0f;
        tensor_out[tid] = x * ratio;

        // mode 1: element-wise clamp
        else;
        tensor_out[tid] = clamp(x, cb.clip_lo, cb.clip_hi);
    }
}


