// Generated by KLSL compiler v0.1
// Shader: fold_forward

StructuredBuffer<int> tokens : register(t0);
StructuredBuffer<float> embed_w : register(t1);
StructuredBuffer<float> attn_w : register(t2);
StructuredBuffer<float> mlp_w : register(t3);
RWStructuredBuffer<float> hidden_out : register(u0);
RWStructuredBuffer<float> logit_out : register(u1);
ConstantBuffer<FwdConst> cb : register(b0);

// forward.klsl — xshard fold forward pass
// Embed lookup → causal GQA attention (softcap 30) → SwiGLU MLP → logit softcap 50
// Compile: klslc forward.klsl




// FwdConst: uint seq_len, n_embd, n_vocab; float attn_softcap, logit_softcap, scale

[numthreads(64, 1, 1)]
void fold_forward(uint3 SV_DispatchThreadID : SV_DispatchThreadID)
{
    uint tid = SV_DispatchThreadID.x;
    if (tid >= cb.seq_len) return;

    // Embed lookup + scale by sqrt(n_embd)
    int   tok  = tokens[tid];
    uint  ebase = tok * cb.n_embd;
    float scale = sqrt((float)cb.n_embd);

    float acc = 0.0f;
    for (uint d = 0; d < cb.n_embd; ++d) {
        float e = embed_w[ebase + d] * scale;
        acc += e * attn_w[tid * cb.n_embd + d];
    }

    // Attention score softcap: 30 * tanh(score / 30)
    float capped = cb.attn_softcap * tanh(acc / cb.attn_softcap);

    // SwiGLU: gate * silu(up)
    float gate = mlp_w[tid * 2];
    float up   = mlp_w[tid * 2 + 1];
    float silu = up / (1.0f + exp(-up));
    float mlp  = gate * silu;

    hidden_out[tid] = capped + mlp;

    // Logit softcap: 50 * tanh(logit / 50)
    float logit = capped + mlp;
    logit_out[tid] = cb.logit_softcap * tanh(logit / cb.logit_softcap);
}


