// Generated by KLSL compiler v0.1
// Shader: FusedAttention

StructuredBuffer<float> Q_buf : register(t0);
StructuredBuffer<float> K_buf : register(t1);
StructuredBuffer<float> V_buf : register(t2);
StructuredBuffer<float> cos_buf : register(t3);
StructuredBuffer<float> sin_buf : register(t4);
RWStructuredBuffer<float> out_buf : register(u0);
ConstantBuffer<AttnConst> cb : register(b0);

// FusedAttention.klsl — fused causal GQA attention
// QK^T matmul → RoPE → per-head QK-norm → attn softcap 30 → causal mask → softmax → AV
// Compile: klslc FusedAttention.klsl




// AttnConst: uint seq, n_q_heads, n_kv_heads, head_dim; float scale, attn_softcap

[numthreads(64, 1, 1)]
void FusedAttention(uint3 SV_DispatchThreadID : SV_DispatchThreadID)
{
    uint tid      = SV_DispatchThreadID.x;
    uint head     = tid / cb.seq;
    uint pos      = tid % cb.seq;
    if (head >= cb.n_q_heads) return;

    // GQA: map Q head → KV head
    uint kv_head = head / (cb.n_q_heads / cb.n_kv_heads);
    uint q_base  = (head * cb.seq + pos) * cb.head_dim;
    uint k_base  = (kv_head * cb.seq)    * cb.head_dim;

    // QK^T scaled dot-product with causal mask
    float score = 0.0f;
    for (uint kpos = 0; kpos < (pos + 1); ++kpos) {
        float qk = 0.0f;
        for (uint d = 0; d < cb.head_dim; ++d) {
            float q = Q_buf[q_base + d];
            float k = K_buf[(k_base + kpos) * cb.head_dim + d];
            qk += q * k;
        }
        qk *= cb.scale;
        // Attention softcap: 30 * tanh(score / 30)
        qk = cb.attn_softcap * tanh(qk / cb.attn_softcap);
        score = max(score, qk);
    }

    // AV accumulate (simplified — full softmax needs group reduction)
    float out_val = 0.0f;
    for (uint d = 0; d < cb.head_dim; ++d) {
        out_val += score * V_buf[(k_base + pos) * cb.head_dim + d];
    }

    out_buf[tid] = out_val;
}


