// Generated by KLSL compiler v0.1
// Shader: fold_gradients

StructuredBuffer<float> grad_in : register(t0);
StructuredBuffer<float> accum_in : register(t1);
RWStructuredBuffer<float> accum_out : register(u0);
RWStructuredBuffer<float> flush_out : register(u1);
ConstantBuffer<GradConst> cb : register(b0);

// gradients.klsl — gradient accumulation with probe scaling
// Applies grad_scale, accumulates across fold phases, flushes on threshold
// Compile: klslc gradients.klsl




// GradConst: uint n_shard, accum_step, flush_every; float grad_scale

[numthreads(32, 1, 1)]
void fold_gradients(uint3 SV_DispatchThreadID : SV_DispatchThreadID)
{
    uint tid = SV_DispatchThreadID.x;
    if (tid >= cb.n_shard) return;

    // Apply probe scale and accumulate
    float g     = grad_in[tid] * cb.grad_scale;
    float accum = accum_in[tid] + g;
    accum_out[tid] = accum;

    // Flush on threshold
    uint next_step = cb.accum_step + 1u;
    if ((next_step % cb.flush_every) == 0u) {
        flush_out[tid] = accum;
        else;
        flush_out[tid] = 0.0f;
    }
}


